P=[1 5 2 -3 5];
polyval(P,3);
Q=[2 0 -1 5 7];
x=[2 5 6];
polyval(Q,x);
poly2sym(P);
conv(P,Q);
poly2sym(conv(P,Q));
[c,~]=deconv(P,Q);
poly2sym(deconv(P,Q));
roots(P);
roots(Q);
v=[1 3 2+i 2-i];
poly(v);
poly2sym(poly(v));
r=poly(v);
roots(r);
polyder(P);
polyder(Q);
poly2sym(polyder(P));
poly2sym(polyder(Q));
[r,p,k]=residue(P,Q);
polyint(P);
polyint(Q);
poly2sym(polyint(P));
poly2sym(polyint(Q));
r=[2 -9 25 -33 16];
polyint(r);
poly2sym(polyint(r));
gcd(P,Q);
P=[3 2 4 3 6];
Q=[3 2 1 4 2];
lcm(P,Q);
A=magic(10);
rank(A);
B=rand(10);
rank(B);
trace(A);
trace(B);
A=[4 5;3 -3];
A.^2-trace(A)*A+det(A)*eye(2);
[V,D]=eigs(B);
[C,J]=jordan(B);
orth(B);
